### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by wanghui0574xs** [matrixssl/matrixssl#16] opened 2017-07-28 09:12 UTC
crypto/math/pstmnt.c
857 line: pstmnt_mult(a, a, r, n);  "n" undefined.  n --> sz

**Comment by CarloWood** [comment] 2019-08-22 16:41
Duplicate of https://github.com/matrixssl/matrixssl/issues/15 (fixed)

**Closed** 2019-10-09 10:22 UTC
