### ISSUE TITLE
typo in line 857 of pstmnt.c

### ISSUE THREAD

**Issue by gitcnd** [matrixssl/matrixssl#18] opened 2017-10-06 15:37 UTC
This line:
`    pstmnt_mult(a, a, r, n);
`
is probably supposed to be:-
`    pstmnt_mult(a, a, r, sz);
`

```
math/pstmnt.c: In function 'pstmnt_square':
math/pstmnt.c:857:26: error: 'n' undeclared (first use in this function)
     pstmnt_mult(a, a, r, n);
                          ^

```

**Comment by CarloWood** [comment] 2019-08-22 16:41
Duplicate of https://github.com/matrixssl/matrixssl/issues/15 (fixed)

**Closed** 2019-10-09 10:34 UTC
